# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_user_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accaunt',
            field=models.CharField(choices=[('Close', 'Close'), ('Open', 'Open')], default='Open', max_length=10),
        ),
    ]
